In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.ndim  # axis(축)의 수 반환

2

In [5]:
a.shape

(2, 3)

In [6]:
a.size

6

In [7]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [8]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
b.ndim

3

In [10]:
f = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
f[0,2]

3

In [12]:
f[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [13]:
g = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [14]:
g.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
g.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
g.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

pandas

In [17]:
import pandas as pd

In [18]:
a = pd.Series(['a','b','c'], index = [1,2,3])

In [19]:
test = {'Name': ['Jone', 'anna', 'peter'],
       'Location': ['New York', 'Paris', 'Berlin'],
       'Age':[24,12,45]}

In [20]:
test_pd = pd.DataFrame(test)

In [21]:
test_pd[test_pd.Age>15]

Name  Location  Age
0   Jone  New York   24
2  peter    Berlin   45

In [22]:
test_pd['Name']

0     Jone
1     anna
2    peter
Name: Name, dtype: object

In [23]:
test_pd[['Name','Location']][0:2]

Name  Location
0  Jone  New York
1  anna     Paris

In [24]:
test_pd[:2]

Name  Location  Age
0  Jone  New York   24
1  anna     Paris   12

In [25]:
test_pd[1:]

Name Location  Age
1   anna    Paris   12
2  peter   Berlin   45

In [26]:
test_pd

Name  Location  Age
0   Jone  New York   24
1   anna     Paris   12
2  peter    Berlin   45

In [27]:
test_pd.iloc[0]

Name            Jone
Location    New York
Age               24
Name: 0, dtype: object

In [28]:
test_pd.iloc[[0,2],[0,2]]

Name  Age
0   Jone   24
2  peter   45

In [29]:
test_pd.iloc[2]

Name         peter
Location    Berlin
Age             45
Name: 2, dtype: object

In [30]:
# test_pd.iloc['Name']  # 이름 사용 불가

In [31]:
# test_pd.loc['Name']

In [32]:
test_pd['Name']

0     Jone
1     anna
2    peter
Name: Name, dtype: object

In [33]:
test_pd.iloc[0]

Name            Jone
Location    New York
Age               24
Name: 0, dtype: object

In [34]:
test_pd.loc[0]

Name            Jone
Location    New York
Age               24
Name: 0, dtype: object

In [35]:
test_pd = test_pd.reindex(index = [0,2,1])

In [36]:
test_pd

Name  Location  Age
0   Jone  New York   24
2  peter    Berlin   45
1   anna     Paris   12

In [37]:
test_pd["Hobby"] = ["Books","Cartoons","Movies"]

In [38]:
test_pd

Name  Location  Age     Hobby
0   Jone  New York   24     Books
2  peter    Berlin   45  Cartoons
1   anna     Paris   12    Movies

In [39]:
test_pd = pd.DataFrame(test_pd, columns=['Name', 'Age', 'Location', 'Hobby'])  # 컬럼 순서 변경

In [40]:
test_pd.loc[3] = ["Alex",28,"Los Angeles", "Books"]

In [41]:
test_pd

Name  Age     Location     Hobby
0   Jone   24     New York     Books
2  peter   45       Berlin  Cartoons
1   anna   12        Paris    Movies
3   Alex   28  Los Angeles     Books